name: unvanquished # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.53.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: A real-time strategy game played as a first-person shooter
description: |
   Unvanquished is a free, open-source FPS game with RTS elements, facing off technologically advanced humans against monstrous aliens. Players can choose either team, and must maintain a base while attempting to destroy enemy base structures. Humans rely on a broad variety of weapons and futuristic equipment, while aliens utilize claws, poisonous bites, and more.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  unvanquished_icon.png
title: Unvanquished

apps:
  unvanquished:
    command: UnvanquishedUpdater
parts:
  unvanquished:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      unvanquished: build/
      unvanquished.1: man/man1/

architectures:
  - build-on: amd64

